### ISSUE TITLE
H3 Registrar Usuario

### ISSUE THREAD

**Issue by LucasColman** [LucasColman/Integrador-POO2#28]
Como usuario del sistema 
Quiero crear una cuenta 
Para poder utilizar las funcionalidades del sistema.

Tareas
- [x] Diseño del wireframe #33 
- [x] Descripción del caso de uso #32 
- [x] Creación del modelo de datos/Base de datos #30 
- [x] Desarrollo interfaz de usuario #31  
- [x] Desarrollo del Backend   #29
